{{- if and .Values.persistence.prompts.enabled (not .Values.persistence.prompts.hostPath.enabled) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "siloprompts.fullname" . }}-prompts-pvc
  labels:
    {{- include "siloprompts.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.prompts.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.prompts.size }}
  {{- if .Values.persistence.prompts.storageClass }}
  storageClassName: {{ .Values.persistence.prompts.storageClass }}
  {{- end }}
{{- end }}
---
{{- if and .Values.persistence.data.enabled (not .Values.persistence.data.hostPath.enabled) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "siloprompts.fullname" . }}-data-pvc
  labels:
    {{- include "siloprompts.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
  {{- end }}
{{- end }}
