apiVersion: v1
kind: Secret
metadata:
  name: {{ include "siloprompts.fullname" . }}-secret
  labels:
    {{- include "siloprompts.labels" . | nindent 4 }}
type: Opaque
stringData:
  secretKey: {{ .Values.secret.secretKey | quote }}
